"""Offline integration of snapshot selection, closing, rebalance and next day."""

import contextlib
import importlib.util
import io
import json
import unittest
from datetime import datetime, timezone
from decimal import Decimal
from pathlib import Path
from unittest.mock import patch
from urllib.parse import parse_qs, urlparse

import test_rebalance_daily as fixtures
from crypto_index import cli


SCRIPT = Path(__file__).resolve().parents[1] / 'scripts' / 'update_daily.py'
SPEC = importlib.util.spec_from_file_location('circuit_update_daily', SCRIPT)
daily = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(daily)


class DailyCircuitTests(unittest.TestCase):
    def test_selection_closing_rebalance_next_day_and_replay(self):
        fixture = fixtures.RebalanceDailyTests()
        self.addCleanup(fixture.doCleanups)
        fixture.setUp()
        root = fixture.root
        # Replace the unit-test closing with an observation generated by the updater.
        fixture.closing_path.unlink()
        history = b'date,value_usdt,index_level\n2026-09-29,100,100\n'
        (root / 'history_seed.csv').write_bytes(history)
        seed_hash = fixtures.module.digest(fixture.prior.read_bytes())
        manifest = {
            'history_file': 'history_seed.csv',
            'portfolio_file': 'portfolio_seed.json',
            'sha256': {'history_seed.csv': fixtures.module.digest(history),
                       'portfolio_seed.json': seed_hash},
        }
        (root / 'manifest.json').write_text(json.dumps(manifest), encoding='utf-8')

        # Run the real scheduled selection entry point with simulated providers.
        output = root / 'snapshots'
        def provider(url):
            self.assertIn(url, (cli.CMC, cli.BINANCE))
            return json.dumps(fixture.cmc if url == cli.CMC else fixture.exchange).encode()

        args = ['crypto_index.cli', '--scheduled', '--output', str(output),
                '--registry', str(fixture.selection / 'registry.json')]
        with (patch('sys.argv', args), patch.object(cli, 'fetch', side_effect=provider),
              patch.object(cli, 'utcnow', return_value=cli.timestamp(fixture.captured)),
              contextlib.redirect_stdout(io.StringIO())):
            self.assertEqual(cli.main(), 0)
        selection = output / '2026-09'
        report = json.loads((selection / 'report.json').read_bytes())
        self.assertEqual(report['status'], 'composition_ready')
        self.assertEqual(len(report['universe']), 15)
        self.assertEqual(report['cash_weight_pct'], 90)

        calls = []
        def prices(url):
            query = parse_qs(urlparse(url).query)
            pair = query['symbol'][0]
            start = int(query['startTime'][0])
            day = datetime.fromtimestamp(start / 1000, timezone.utc).date().isoformat()
            key = (pair, day)
            expected = {('BTCUSDT', '2026-09-30'): '110',
                        ('ETHUSDT', '2026-09-30'): '5',
                        ('ETHUSDT', '2026-10-01'): '6'}
            self.assertIn(key, expected)
            calls.append(key)
            price = expected[key]
            return json.dumps([[start, price, price, price, price, '10',
                                start + 59999, '100', 3]]).encode()

        def update(day):
            class Clock(datetime):
                @classmethod
                def now(cls, tz=None):
                    value = cls.fromisoformat(day + 'T13:02:00+00:00')
                    return value.astimezone(tz) if tz else value.replace(tzinfo=None)
            with (patch.object(daily, 'ROOT', root), patch.object(daily, 'datetime', Clock),
                  patch.object(daily, 'download_bytes', side_effect=prices),
                  contextlib.redirect_stdout(io.StringIO())):
                daily.main()

        update('2026-09-30')
        closing_raw = fixture.closing_path.read_bytes()
        closing = json.loads(closing_raw)
        self.assertEqual(Decimal(closing['value_usdt']), Decimal('101'))
        self.assertEqual(closing['portfolio_sha256'], seed_hash)
        self.assertEqual(calls, [('BTCUSDT', '2026-09-30')])

        destination = fixtures.module.run(root, fixture.prior, selection, '2026-09-30',
                                          now=fixture.now, fetch=prices)
        portfolio_raw = destination.read_bytes()
        portfolio = json.loads(portfolio_raw)
        self.assertEqual(Decimal(portfolio['index_level']), Decimal('101'))
        self.assertEqual(Decimal(portfolio['cash_usdt']), Decimal('90.9'))
        self.assertEqual(portfolio['positions'][0]['asset'], 'ETH')
        self.assertEqual(Decimal(portfolio['positions'][0]['quantity']), Decimal('2.02'))
        self.assertEqual(fixture.closing_path.read_bytes(), closing_raw)

        update('2026-10-01')
        following = json.loads((root / 'observations' / '2026-10-01.json').read_bytes())
        self.assertEqual(following['portfolio_sha256'], fixtures.module.digest(portfolio_raw))
        self.assertEqual(set(following['prices_usdt']), {'ETH'})
        self.assertEqual(Decimal(following['value_usdt']), Decimal('103.02'))
        self.assertEqual(Decimal(following['index_level']), Decimal('103.02'))
        self.assertEqual(Decimal(following['daily_return_pct']), Decimal('2'))
        self.assertEqual(Decimal(following['cumulative_return_pct']), Decimal('3.02'))
        self.assertEqual(calls, [('BTCUSDT', '2026-09-30'), ('BTCUSDT', '2026-09-30'),
                                 ('ETHUSDT', '2026-09-30'), ('ETHUSDT', '2026-10-01')])

        def snapshot():
            return {str(p.relative_to(root)): p.read_bytes()
                    for p in root.rglob('*') if p.is_file()}
        before = snapshot()
        calls_before = list(calls)
        update('2026-10-01')
        self.assertEqual(calls, calls_before)
        self.assertEqual(snapshot(), before)
        with self.assertRaises(FileExistsError):
            fixtures.module.run(root, fixture.prior, selection, '2026-09-30',
                                now=fixture.now, fetch=prices)
        self.assertEqual(snapshot(), before)
        self.assertFalse((root / 'update.lock').exists())


if __name__ == '__main__':
    unittest.main()
